name: periscope
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - tqdm
  - plotnine
  - pandas
  - samtools
  - numpy
  - pysam
  - minimap2
  - bwa
  - bedtools
  - biopython=1.74
  - pybedtools
  - snakemake-minimal=5.13
  - pytest
  - pip
  - pip:
    - git+https://github.com/artic-network/fieldbioinformatics.git@3b6c1f3