name: periscope
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pysam
  - biopython
  - pybedtools
  - pip
  - pip:
    - git+https://github.com/artic-network/fieldbioinformatics.git